version: 1
validation: sovereign
accounts:
  - name: alice
    coins:
      - 20000sputnik
      - 20000000000usputnik
  - name: bob
    coins:
      - 100sputnik
      - 100000000usputnik
client:
  openapi:
    path: docs/static/openapi.yml
faucet:
  name: bob
  coins:
    - 5sputnik
    - 100000usputnik
validators:
  - name: alice
    bonded: 1000000000usputnik
genesis:
  app_state:
    staking:
      params:
        bond_denom: "usputnik"
