version: 1
validation: sovereign
accounts:
  - name: alice
    coins: ["20000sputnik", "20000000000usputnik"]
  - name: bob
    coins: ["10000sputnik", "10000000000usputnik"]
client:
  openapi:
    path: docs/static/openapi.yml
validators:
  - name: alice
    bonded: "1000000000usputnik"
genesis:
  app_state:
    staking:
      params:
        bond_denom: "usputnik"
    crisis:
      constant_fee:
        denom: "usputnik"
        amount: "1000"
    mint:
      params:
        mint_denom: "usputnik"
    gov:
      deposit_params:
        min_deposit:
          - denom: "usputnik"
            amount: "10000000"
      params:
        expedited_min_deposit:
          - denom: "usputnik"
            amount: "50000000"
        min_deposit:
          - denom: "usputnik"
            amount: "10000000"
